### ISSUE TITLE
Guide on command based programming

### ISSUE THREAD

**Issue by FernTemp** [frc2609/rapid-react-robot-code-2022#11]
https://docs.google.com/presentation/d/1kVDppzkow4M19QsfyUDZrhe_evU_ATksjlAW-aqYXe8

This slideshow is for the older command based framework, but a lot of it still applies

**Comment by FernTemp** [comment]
@UserC2 @WhyNot180 Here is a good start to learning about command based programming

**Comment by theyeeman** [comment]
Opting to close this issue for now
