### ISSUE TITLE
Create constant variables for controller button/axis numbering

### ISSUE THREAD

**Issue by FernTemp** [frc2609/rapid-react-robot-code-2022#13]
Create constant for each button/axis number on the Xbox controller. For example, instead of this:
```
setHook(-m_stick.getRawAxis(5));
```
we create a constant in the `Constant.java` file:
```
public final class Constants {
    public static final int RIGHT_STICK_X_AXIS = 5;  // not sure if this is the correct number but this is just an example
}
```

and use this constant instead of hard coding the numbers:
```
setHook(-m_stick.getRawAxis(Constant.RIGHT_STICK_X_AXIS));
```

**Comment by UserC2** [comment]
There is an XboxController class for this purpose...

**Comment by UserC2** [comment]
Unfortunately, the Joystick class doesn't have any button mappings since its meant to be compatible with as many controllers as possible.

**Comment by theyeeman** [comment]
> There is an XboxController class for this purpose...

Interesting, I didn't know that! Maybe we can use that class to make the code easier to read

**Comment by UserC2** [comment]
https://prod.liveshare.vsengsaas.visualstudio.com/join?E49D18B0EC8911E10E2E095FC71E53565315
Live Share Link
