### ISSUE TITLE
Figure out which files can be removed

### ISSUE THREAD

**Issue by FernTemp** [frc2609/rapid-react-robot-code-2022#14]
There might be some junk files in `src/main/java/frc/robot`, so go through each one and see which can be removed.

![files to check](https://user-images.githubusercontent.com/99444930/153734450-9da58a83-9161-494a-a8dc-eb10fea1f93d.png)

**Comment by UserC2** [comment]
**KEEP**
`Main.java`, `Robot.java`, and `RobotContainer.java` are required

`Constants.java` is useful
`Commands/SetArm.java` is useful

Everything in `Subsystems` is useful

**CONSIDER REMOVING**
(In order of priority)
1. `ManualHookDrive.java` and `PrintConsole.java` are empty and unused. `PrintConsole.java` may be useful in the future, but it currently contains nothing, so it can be deleted
2.  `ClimbingSequence.java` contains very little code, which only sets the arm to 98.15 degrees. It is not useful.
2. `Traverse.java` and `TraverseBack.java` are replaced by changes to `Climber.java` allowing for manual control of the climber, but may be useful in case autonomous control is ever re-added
3. `WaitForButtonPress.java` is used only in `ClimbingSequence.java`, which is empty and unused, but WaitForButtonPress could potentially be useful in the future.

**Comment by theyeeman** [comment]
Thanks for the investigation! Let's try to solve this issue during the next meeting

**Comment by FernTemp** [comment]
This issue isn't really relevant anymore since the shooter and climbing code are on separate branches. We can look at this issue once we merge the two together
