### ISSUE TITLE
Lay out steps for climbing and document this

### ISSUE THREAD

**Issue by FernTemp** [frc2609/rapid-react-robot-code-2022#15]
We need concrete list of steps on how to achieve climbing, and we need this documented. Discuss things such as how we want the robot to climb up, whether we will use swinging or not, whether we want to use the base of the robot as a counter weight, etc.

**Comment by theyeeman** [comment]
There is a powerpoint that shows the steps for climbing on Discord. Message is pinned in climbing channel
