### ISSUE TITLE
setArmPosition parameter in Traverse is unclear

### ISSUE THREAD

**Issue by UserC2** [frc2609/rapid-react-robot-code-2022#24]
`m_climber.setArmPosition(77.64+((101-77.64)*progress));`

*Why* is this value that is being calculated? This line is also used in TraverseBack. 

Could this value be calculated in a function so it can be reused in TraverseBack?

Related to issue #20

**Comment by gregzetko** [comment]
77.64 is the shallowest angle we would like to reach, 101 is the widest angle we want to achieve, and progress is a number from 0 to 1 describing how far along the slider the hooks are. This was connecting the two motors for one joystick, but are likely no longer needed as per Antoine's step by step climb explanation

**Comment by theyeeman** [comment]
Since we are no longer using this line of code, this issue can be closed
