### ISSUE TITLE
Color sensor subsystem takes > 20 ms to execute

### ISSUE THREAD

**Issue by UserC2** [frc2609/rapid-react-robot-code-2022#35]
Currently you can disable it by commenting out the color sensor line in `RobotContainer.java`:

```java
//public final ColorSensing m_colorSubsystem = new ColorSensing();
```

**Comment by UserC2** [comment]
See #37, we could potentially use our own code instead of using the supplied library

**Comment by theyeeman** [comment]
This ticket may be closed if we fully commit to not using colour sensors on the robot. Waiting for further instructions from Antoine

**Comment by FernTemp** [comment]
Closing this issue since it seems we will not be using colour sensor
