### ISSUE TITLE
Check ball color and write custom color sensing code

### ISSUE THREAD

**Issue by UserC2** [frc2609/rapid-react-robot-code-2022#37]
1. Print R, G, B values for color sensor to Smart Dashboard
2. Check red ball and write down R, G, B values for red ball
3. Check blue ball and repeat above steps
4. Write custom color sensing code that will compare R, G, B values and output which ball it is currently sensing, or no ball if it isn't close enough to each color.

We should probably also check what the color sensor values are when it isn't pointing at anything.

**Comment by theyeeman** [comment]
This ticket may be closed if we fully commit to not using colour sensors on the robot. Waiting for further instructions from Antoine

**Comment by FernTemp** [comment]
Closing this issue since it seems we will not be using colour sensor
