### ISSUE TITLE
Merge climbing code into logger branch

### ISSUE THREAD

**Issue by theyeeman** [frc2609/rapid-react-robot-code-2022#40]
Merge the new climbing code into the `logger` branch so Greg can log data while climbing.

- [x] fix column headers so they display the correct text in the correct order (https://github.com/frc2609/rapid-react-robot-code-2022/blob/2723fbcbe088886830b64efc770553a235e4dc4e/src/main/java/frc/robot/subsystems/Logger.java#L61)
  - use the [variables here](https://github.com/frc2609/rapid-react-robot-code-2022/blob/2723fbcbe088886830b64efc770553a235e4dc4e/src/main/java/frc/robot/subsystems/Logger.java#L87-L97) for the column names
- [x] reformat the code so it's pretty
- [x] [fix filename to have `.csv` ending instead of `.txt`](https://github.com/frc2609/rapid-react-robot-code-2022/blob/2723fbcbe088886830b64efc770553a235e4dc4e/src/main/java/frc/robot/subsystems/Logger.java#L73-L77)

**Comment by FernTemp** [comment]
Code seems to work. [Use `climbing-logging branch`](https://github.com/frc2609/rapid-react-robot-code-2022/tree/climbing-logging)
