### ISSUE TITLE
Rename Constants

### ISSUE THREAD

**Issue by UserC2** [frc2609/rapid-react-robot-code-2022#41]
Instead of something like `XboxConstants.X_BUTTON`, we could use `Constants.Xbox.X_BUTTON`
It would reduce the amount of imports and get rid of the Constants suffix.

Also, PwmMotorId could be PWM instead (easier to type) and it's still clear, same with CAN:
`Constants.PWM.LOWER_BELT_MOTOR`

**Comment by theyeeman** [comment]
Yeah, I like your naming scheme better. In the `shooter-intake` branch, I already created classes in the `Constants` class, so it should be pretty fast to rename the symbol and the change should propagate throughout the code (I can do this)

**Comment by FernTemp** [comment]
Constants have been renamed
