### ISSUE TITLE
Shooter tasks

### ISSUE THREAD

**Issue by theyeeman** [frc2609/rapid-react-robot-code-2022#43]
- 4 buttons for controlling shooter
  - 1 button to intake a ball and stage it for launch
    - need to figure out which motors can be controlled/which ones to spin to stage without launching
  - 1 button to rotate the turret and bring flywheel up to speed (vibrate controller or some other prompt to let operator know that everything is ready to launch)
    - do we need a backup mode in case auto aim fails? i don't know if we have enough buttons
  - 1 button to launch ball after turrent and flywheel is ready
  - 1 button to bring flywheel up to low speed (maybe 10%?) just to eject any ball we don't want

**Comment by UserC2** [comment]
- Intake a ball and stage it for launch -> You need to spin the intake motor and the **LOWER** belt motor. (This is already mapped to `A` in the `shooter-practice` branch)
- Button to rotate the turret and bring flywheel up to speed -> Could we use `B` for this? It is already used to spin up the upper belt, which causes the ball to be shot by the shooter, and using it to prepare another shot would be similar to its current use
- We have enough buttons for backup mode
- Button to launch ball -> **IF** the operator is **NOT** climbing the robot, we can use right trigger (bonus: it's usually mapped as shoot in most games, so it will feel familiar)
- Button for low speed ejection of ball -> Could use X for this, close to A and B and is unused currently

**Comment by UserC2** [comment]
Did not mean to close the issue.
Backup mode:
- You could press start or select to activate it
- You could use the same D-Pad setup as we have now to set the speed the ball is shot at, and B to activate the motors, and right trigger to shoot
- If you wanted to rotate the turret in backup mode that can be mapped to the operator's left joystick which currently isn't used

**Comment by FernTemp** [comment]
- ~Need to tune limelight further~ need to tune to each field
- ~Try to generate equation for flywheel rpm and hood pos~ done, just need to test and tune
- ~Properly mount limelight so it doesn't move around~
- ~tune turret rotation proportional value~ done

**Comment by theyeeman** [comment]
Opting to close issue
