### ISSUE TITLE
Saturday, March 5th tasks

### ISSUE THREAD

**Issue by FernTemp** [frc2609/rapid-react-robot-code-2022#44]
- tune flywheel motors so actual rpm has good tracking on set point rpm
- mark set distances from the goal and shoot ball
  - record the distance and rpm
  - we currently don't have hood motor control, so fix hood position
- see if there is a relation between all the recorded distance and rpm
  - try to create an equation to fit the points (excel seems like a good candidate for this)
- once equation is determined (if there is one), implement it and try it

**Comment by FernTemp** [comment]
Use this branch (https://github.com/frc2609/rapid-react-robot-code-2022/tree/fy-flywheel-tuning) for flywheel tuning (can enter all values into SmartDashboard)

**Comment by FernTemp** [comment]
Notes:
- Not going to try to get perfect tracking with RPM
  - it's a little off (max ~100 rpm from setpoint) but should be okay
- measured 0 to 3 feet distances, but can't go further since we need hood adjustment and that is not mounted/set up yet

**Comment by FernTemp** [comment]
Improved PID tracking. Changed the feedforward gain to `0.000183`

**Comment by theyeeman** [comment]
Closing because old
