### ISSUE TITLE
Turning too sensitive?

### ISSUE THREAD

**Issue by WhyNot180** [frc2609/rapid-react-robot-code-2022#65]
Turning at full speed is prone to bouncing the robot. Curvature drive may be a possible solution, but testing is required.

**Comment by theyeeman** [comment]
We can see if Dom wants to lower the max turning speed on the robot. All we would need to do is add a multiplier to the x-axis of the joystick for manual drive. Ask him today if he wants to lower the max turning speed

**Comment by WhyNot180** [comment]
Closed _**after**_ the comp is over lol
